# Generated by Django 4.2.1 on 2023-06-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_datalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='value',
        ),
        migrations.AddField(
            model_name='datalog',
            name='ch_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datalog_ch1', to='realtime.channel'),
        ),
        migrations.AddField(
            model_name='datalog',
            name='ch_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datalog_ch2', to='realtime.channel'),
        ),
        migrations.AddField(
            model_name='datalog',
            name='ch_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datalog_ch3', to='realtime.channel'),
        ),
        migrations.AddField(
            model_name='datalog',
            name='ch_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datalog_ch4', to='realtime.channel'),
        ),
    ]
