# Generated by Django 4.2.1 on 2023-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_remove_datalog_channel_remove_datalog_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='ch_1',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='ch_2',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='ch_3',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='ch_4',
            field=models.JSONField(),
        ),
    ]
