# Generated by Django 4.2.1 on 2023-06-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_alter_datalog_ch_1_alter_datalog_ch_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalog',
            old_name='ch_1',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='ch_2',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='ch_3',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='ch_4',
        ),
    ]
