# Generated by Django 4.2.1 on 2023-06-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0007_connectionslostlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
