# Generated by Django 4.2.1 on 2023-06-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0009_rename_channellog_channellogstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channellogstatus',
            options={'verbose_name': 'Channel Log Status'},
        ),
    ]
