# Generated by Django 4.2.1 on 2023-06-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0011_alter_channellogstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channellogstatus',
            options={'verbose_name': 'Channel Logs Status', 'verbose_name_plural': 'Channel Logs Status'},
        ),
    ]
