# Generated by Django 4.2.1 on 2023-07-13 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0014_customname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customname',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
