# Generated by Django 4.2.1 on 2023-07-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0015_customname_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customname',
            options={'ordering': ['-created']},
        ),
    ]
